### ISSUE TITLE
Debuffs shifting to bottom right with many status afflictions

### ISSUE THREAD

**Issue by pireuslejonet** [rgd87/BigPlayerDebuffs#2]
When using Display Target Info Independently for Target Info in the HUD Layout and many statuses are affecting the target some (or just one, haven't tested enough) will be shifted to the bottom right. Such as below:

![2021-12-14 - 16 44 05](https://user-images.githubusercontent.com/93527189/146072521-dcf4fefa-e8bd-490f-9a3a-923543fce4ff.png)

With my current HUD settings (they are all scaled to 100%):
![2021-12-14 - 16 44 22](https://user-images.githubusercontent.com/93527189/146072622-90be4041-eb49-43a5-b17e-19fcdab90784.png)

I assume something's being weird with the resizing and all.

**Comment by d87** [comment]
should be fixed in 1.1.0.3
