### ISSUE TITLE
Plugin breaking on next Dalamud update

### ISSUE THREAD

**Issue by Aireil** [rgd87/BigPlayerDebuffs#5]
https://github.com/rgd87/BigPlayerDebuffs/blob/361cf69223763d43bd1a14a3ff93071538dc0e3c/BigPlayerDebuffs.cs#L95
Hey, you shouldn't init Dalamud's client struct, this is only if you provide your version of the library with your plugin.
This didn't use to be a problem, but a recent update of client struct will require plugins using this init method to be recompiled, so you can just remove the line altogether while you're at it :).

**Comment by d87** [comment]
Thanks for letting me know, done
