### ISSUE TITLE
Increasing the size further

### ISSUE THREAD

**Issue by Efiyo** [rgd87/BigPlayerDebuffs#8]
Hi, I know this might be a niche request, but I was wondering if it would be possible to make the bar go past 2.0 size or maybe letting us input a value?

**Comment by d87** [comment]
Hi, alright, in the future updates, but for now you could edit C:\Users\<you>\AppData\Roaming\XIVLauncher\pluginConfigs\BigPlayerDebuffs.json
to go beyond 2
